Dhtarc stability test
holochain/holochain pull request #1135
Opened 2021-11-18 08:49 UTC by freesig

### Summary

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

2021-12-16 00:00 UTC, maackle approved these changes

2021-12-16 00:05 UTC, maackle commented
This is lots of lines, but 500+ of them are from an ignored test

2021-12-16 21:21 UTC, neonphog commented on crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
> +                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
^^ Is this an accident from debugging? I don't think we want to be updating the agent info every 5 seconds...

2021-12-16 21:21 UTC, neonphog commented on crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
> +    dbg!(density.expected_count());
should this be a trace or removed?

2021-12-16 21:21 UTC, neonphog commented on crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs
> +            // .unwrap_or_else(|| DhtArc::with_coverage(agent.get_loc(), 0.1))
remove or comment?

2021-12-16 21:25 UTC, neonphog commented on crates/kitsune_p2p/dht_arc/src/peer_view/peer_view_beta.rs
> +    fn check_focused_view(&self, arc: DhtArc, peers: &[DhtArc], focus_size: usize) -> Option<f64> {
I'm not sure I agree with the philosophy of this function... The only property to me that seems to make for an accurate extrapolation would be completeness of data, and we're making no effort to be more complete in the area closer to us than further away. And if we *do* have complete data for the full area locally, is there any benefit in not using it?

2021-12-16 21:27 UTC, neonphog requested changes
Marking as "Request changes" for the 5 second agent info update. I'm fine merging with the 'check_focused_view' thing since it's been tested with it, just want it to be a consideration for any future work.

2021-12-20 01:32 UTC, freesig commented
@maackle Can I rebase this onto develop. I'm not sure this diff actually represents what we are wanting to merge to develop?

2021-12-20 15:23 UTC, maackle commented
Sure rebase it, but I did merge develop into the feature branch and this
branch a few days ago.

On Sun, Dec 19, 2021, 5:32 PM Tom ***@***.***> wrote:

> @maackle <https://github.com/maackle> Can I rebase this onto develop. I'm
> not sure this diff actually represents what we are wanting to merge to
> develop?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/holochain/holochain/pull/1135#issuecomment-997517261>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAG2ZZTNXZXSHSAAZA6336TUR2BS7ANCNFSM5IJBA3OA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-13 15:34 UTC, neonphog approved these changes

2022-01-18 00:32 UTC, maackle approved these changes
I still approve

2022-01-31 06:39 UTC, merged