examples of how to handle properties
holochain/holochain pull request #1138
Opened 2021-11-22 20:59 UTC by thedavidmeister

### Summary

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

2021-11-22 21:30 UTC, timotree3 commented
This is great documentation but do you expect people to see this? Will this be linked to from somewhere?

2021-11-23 16:58 UTC, neonphog commented
> This is great documentation but do you expect people to see this? Will this be linked to from somewhere?

api docs are where it's at, if folks aren't looking there, we need to train them to : )

2021-11-23 16:59 UTC, neonphog commented on crates/test_utils/wasm/wasm_workspace/zome_info/src/lib.rs
> +/// Yaml doesnt enforce the type of any value.
```suggestion
/// Yaml doesn't enforce the type of any value.
```

2021-11-23 16:59 UTC, neonphog commented on crates/test_utils/wasm/wasm_workspace/zome_info/src/lib.rs
> +}
```suggestion
}

```

2021-11-23 17:00 UTC, neonphog approved these changes
:+1:

2021-11-23 17:59 UTC, timotree3 commented
@neonphog what do you mean? It looks to me like all the documentation is inside a test DNA's source code. It wouldn't show up in any HDK docs

2022-01-12 06:28 UTC, freesig requested changes

2022-01-12 06:28 UTC, freesig commented on crates/test_utils/wasm/wasm_workspace/zome_info/src/lib.rs
> +struct PropertiesValue(Value);
Why not just move the `YamlProperties` type to the `holochain_zome_types`?

2022-02-01 11:08 UTC, freesig approved these changes

2022-02-01 11:50 UTC, merged

2022-02-01 21:53 UTC, freesig commented
@thedavidmeister This PR is missing a changelog entry