wip on parallel tests
holochain/holochain pull request #1232
Opened 2022-02-15 15:15 UTC by thedavidmeister

### Summary

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

2022-02-15 21:00 UTC, freesig requested changes

2022-02-16 05:23 UTC, thedavidmeister commented on nix/pkgs/core.nix
> +    cargo build --features 'build_wasms' --manifest-path=crates/holochain/Cargo.toml
@freesig because tests fail if it isn't, due to unbuilt wasms

2022-02-16 09:46 UTC, freesig commented on nix/pkgs/core.nix
> +    cargo build --features 'build_wasms' --manifest-path=crates/holochain/Cargo.toml
So this can be down with `cargo build --features 'build_wasms' -p holochain_wasm_test_utils`

2022-02-16 13:58 UTC, steveeJ reviewed
on naming these scripts: how about we keep a common prefix `hc-test-...` so that they're easier to discover with shell completion?

2022-02-16 13:58 UTC, steveeJ commented on nix/pkgs/core.nix
> +    cargo build --features 'build_wasms' -p holochain_wasm_test_utils
the `holochain_wasm_test_utils` crate doesn't have a feature called `build_wasms`. it only has these:

```toml
[features]
default = []
build = []
only_check = []
```

looks like we want `build` here

2022-02-16 13:58 UTC, steveeJ commented on nix/pkgs/core.nix
>      cargo test --lib --manifest-path=crates/test_utils/wasm/wasm_workspace/Cargo.toml --all-features -- --nocapture
how does it work when the `hc-wasm-test` is run separately from the `hc-standard-test`? specifically, how are the wasm files built, or are they not required by this?

2022-02-16 15:00 UTC, steveeJ approved these changes
:+1:

2022-02-16 15:23 UTC, merged