Create input refactor
holochain/holochain pull request #1425
Opened 2022-06-14 04:45 UTC by freesig

### Summary

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

2022-06-17 22:00 UTC, maackle commented on crates/holochain_integrity_types/src/entry.rs
> +/// The data needed to build an [`Entry`] and it's [`Header`](crate::header::Header).
```suggestion
/// The data needed to build an [`Entry`] and its [`Action`](crate::action::Action).
```

2022-06-17 22:01 UTC, maackle commented on crates/holochain_types/src/record.rs
> +    /// Build this element into it's parts for constructing an [`Element`].
```suggestion
    /// Produce the parts needed to construct a [`Record`].
```

2022-06-17 23:16 UTC, maackle requested changes
Looks good, but now I have some concerns about things being called Builders.

2022-06-17 23:16 UTC, maackle commented on crates/holochain/src/test_utils.rs
> +pub trait CreateInputBuilder {
```suggestion
pub trait CreateInputExt {
```

2022-06-17 23:16 UTC, maackle commented on crates/holochain_integrity_types/src/entry.rs
> +pub type RecordBuilder = EntryImpl<AppEntry>;
What do you think about calling this something else? My objections is that this doesn't really evoke [the Builder pattern](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html). `build()` doesn't even produce the thing that this is supposed to be a Builder for (a Record), it just produces some intermediate state, which has to be built up into a record elsewhere.

```suggestion
/// All entry-specific data needed to build a [`Record`](crate::record::Record).
pub type EntryPlus = EntryImpl<AppEntry>;
```

2022-06-17 23:16 UTC, maackle commented on crates/holochain_types/src/record.rs
> +    fn build(self) -> (EntryDefLocation, EntryVisibility, Entry) {
Does this really need to be a trait? Could it just be a method directly on `RecordBuilder` (or whatever we call it)?

Also for the same reason I'd like this not to be called a Builder, I'd like this method to not be called `build`.

```suggestion
impl RecordBuilderHelper for RecordBuilder {
    fn into_parts(self) -> (EntryDefLocation, EntryVisibility, Entry) {
```

2022-06-28 02:12 UTC, jost-s approved these changes
LGTM

2022-06-28 02:30 UTC, maackle approved these changes

2023-11-20 02:43 UTC, closed without merging