Expose all validation types as public in holochain_zome_types crate
holochain/holochain pull request #1457
Opened 2022-06-22 17:20 UTC by abe-njama

### Summary

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

2022-07-29 06:48 UTC, freesig requested changes

2022-07-29 06:48 UTC, freesig commented on crates/holochain_zome_types/src/zome/inline_zome.rs
> +    pub _t: PhantomData<T>,
Hmm maybe remove this one as this is never actually used in the wasm. So it can remain private

2022-07-29 06:48 UTC, freesig commented on crates/holochain_zome_types/src/zome.rs
>      def: T,
Also the def line should be pub

2022-09-01 18:16 UTC, thedavidmeister approved these changes

2022-09-01 18:18 UTC, merged