Docs/hdi
holochain/holochain pull request #1477
Opened 2022-07-06 22:34 UTC by jost-s

### Summary

- Docs: replace references to deprecated macros `entry_def!` and `#[hdk_entry(id..)]`

### TODO:
- [x] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

2022-07-07 02:59 UTC, jost-s commented on crates/hdk/src/lib.rs
> +/// Definitions of entry types belong in the integrity zomes of a DNA. In contrast, operations
@maackle Is there a way to dedup these doc comments? They need to be updated in two different places, the hdk and the hdi crates.

2022-07-07 07:05 UTC, maackle requested changes
Looks like most instances of example snippets using `hdk_entry_helper` need to include an `hdk_entry_defs` enum as well

2022-07-08 19:17 UTC, maackle submitted a review, later dismissed
A few more issues

2022-07-08 19:17 UTC, maackle commented on crates/hdk/src/entry.rs
>  /// let foo_zero_action_hash: ActionHash = commit_entry!(Foo(0))?;
I think commit_entry! is actually outdated, which I didn't catch the first time around.

```suggestion
/// let foo_zero_action_hash: ActionHash = create_entry(EntryTypes::Foo(Foo(0)))?;
```

2022-07-08 19:25 UTC, jost-s commented
@maackle Thanks for spotting that, I was sloppy there. This should be it now.

2022-07-12 02:19 UTC, maackle commented on crates/hdk/src/entry.rs
> +/// let foo_zero_action_hash: ActionHash = create_entry!(EntryTypes::Foo(Foo(0)))?;
It's not a macro

```suggestion
/// let foo_zero_action_hash: ActionHash = create_entry(EntryTypes::Foo(Foo(0)))?;
```

2022-07-12 02:20 UTC, maackle reviewed
I think it's good now! Thanks for the updates

2022-07-12 02:21 UTC, maackle approved these changes

2022-07-12 02:21 UTC, merged