Retry network join on startup
holochain/holochain pull request #2419
Opened 2023-05-23 15:39 UTC by ThetaSinner

### Summary

I was initially thinking that kitsune should take responsibility for this but the `join` operation is important and does need to succeed before the app should be considered active. For that to work though, kitsune would need to understand when it is 'online' and take responsibility for retrying bootstrapping each agent, then communicating that back to the conductor. That mixes responsibilities and seems more complicated than this.

There are two drawbacks to this approach though
- The retryable check is a bit brittle. At the moment the first required network access is a call to the bootstrap server over HTTP which results in a reqwest error. I think this could be addressed by having Kitsune communicate its online/offline state instead of checking the error that's coming back.
- Holochain doesn't finish starting until it has a network connection. This isn't 'bad' necessarily but it's a behavior change

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

2023-05-23 18:10 UTC, jost-s approved these changes
LGTM

2023-05-23 18:10 UTC, jost-s commented on crates/holochain/src/conductor/conductor.rs
> +                    e.is_connect()
`e.is_connect` funny name for a method

2023-05-26 21:01 UTC, maackle requested changes
Looks good, but concerned about a tight, potentially infinite loop

2023-05-26 21:01 UTC, maackle commented on crates/holochain/src/conductor/conductor.rs
> +                                            AppStatusFx::SpinUp
Will this cause an infinite loop of retries if the network can't be joined though? Perhaps there needs to be an exponential backoff or at least delay?

2023-05-30 23:06 UTC, maackle commented on crates/holochain/src/conductor/conductor.rs
> +                                            AppStatusFx::SpinUp
What's the bootstrap connect timeout?

2023-06-02 10:26 UTC, ThetaSinner commented on crates/holochain/src/conductor/conductor.rs
> +                                            AppStatusFx::SpinUp
There are multiple timeouts involved it seems but experimentally it's retrying every 17 second for me. That's a lot of tries if the bootstrap server can't be reached for several hours or more. It's a nice short wait when the server is available again.

2023-06-07 01:26 UTC, maackle commented on crates/holochain/src/conductor/conductor.rs
> +                                            AppStatusFx::SpinUp
I guess that's OK, right? Shouldn't be huge overhead for offline users. I don't think we have bandwidth to do anything more sophisticated like detecting the absence and presence of internet connection, and waiting any longer than 15-30 seconds feels like too long.

2023-06-07 01:26 UTC, maackle approved these changes

2023-06-07 16:13 UTC, ThetaSinner commented on crates/holochain/src/conductor/conductor.rs
> +                                            AppStatusFx::SpinUp
Agreed on both, I think dropping into a network connectivity check with a back-off would be a better solution but not a small bit of work. There is a connectivity check starting in the tx5 repo but it doesn't cover any of the things I think we'd want here like checking for an active network interface, a local gateway and connectivity to the bootstrap server.

2023-06-16 17:36 UTC, merged