build: make sqlite-encrypted a default feature
holochain/holochain pull request #2973
Opened 2023-10-25 20:45 UTC by mattyg

### Summary

Make `sqlite-encrypted` a default feature. I hoped you could override default features for specific build profiles, but I guess not.

Resolves #2957 

### TODO:
- [x] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

2023-10-30 19:39 UTC, jost-s requested changes
This encrypts databases in tests as well. Is there a way to keep them unencrypted? I tried to disable default features for `holochain` in `dev-dependencies`, but the test DBs are still encrypted.

2023-10-30 20:45 UTC, ThetaSinner commented
It should be possible to modify https://github.com/holochain/holochain/pull/2973/files#diff-8c72bca6e5c9cacad5ed1706bcd7a0d9d2a2344fc548c21c826fa20cd4a4309fR121 to read 

```holochain = { path = ".", default-features = false, features = ["test_utils", "slow_tests", "glacial_tests", "sqlite-encrypted", "tx2", "tx5", "metrics_influxive"] }```

I think that'd work right? 

I think there's a bigger problem with this though which is that with this feature enabled Holochain will expect to read existing databases as encrypted. I'm sure SQLite has a mechanism to deal with this but I'm not sure Holochain will cope. I worry that the conductor will recognize existing unencrypted databases as just corrupt or something.

2023-10-30 23:39 UTC, jost-s commented
> It should be possible to modify https://github.com/holochain/holochain/pull/2973/files#diff-8c72bca6e5c9cacad5ed1706bcd7a0d9d2a2344fc548c21c826fa20cd4a4309fR121 to read
> 
> `holochain = { path = ".", default-features = false, features = ["test_utils", "slow_tests", "glacial_tests", "sqlite-encrypted", "tx2", "tx5", "metrics_influxive"] }`
> 
> I think that'd work right?

I thought so too and tried the above but with `"sqlite"` instead of `"sqlite-encrypted"`. It was still encrypted for me.

2023-11-30 15:44 UTC, ThetaSinner commented
I'm going to take a look at this and do a bit of testing. If we can make this a default without breaking existing databases that'd be ideal, I want to see what happens in that case

2023-11-30 17:52 UTC, ThetaSinner commented
When building integration tests Cargo will take the crate, the dependencies and the dev-dependencies, merge it all and build the result. So anything that's in your default features will always be included. That's just how Cargo works currently. I don't like that very much but that seems to be the way it is. If you want an unencrypted database the way to do that is with `cargo test --no-default-features` which gets us back to the current state.

Honestly I so rarely look at the databases created by tests I'm not too concerned by this. I'd also be open to adding a feature to sweettest where we can ask it to just dump the unencrypted databases after the test because they are really supposed to be transient at the moment.

2023-12-01 16:47 UTC, ThetaSinner commented
The other option for testing is actually just to get the sqlcipher version of sqlite and use that to open the files. As long as you know the *super secret* key, you can just open the database files that way :) 

I've updated this PR with a mechanism for automatically switching from unencrypted to encrypted databases. This provides a way forward with encryption now being the default. Especially for Holo to be able to migrate a large number of databases at once.

2023-12-01 17:26 UTC, neonphog approved these changes
Question about locking the database while migrating, but otherwise looks good :+1:

2023-12-01 17:57 UTC, ThetaSinner commented on crates/holochain_sqlite/src/db/access.rs
> +        conn.close().map_err(|(_, err)| err)?;
It seems like it couldn't hurt. I'm not quite clear how that behaves with the WAL but we can at least prevent modifications to the database itself while the migration is happening

2023-12-04 18:17 UTC, jost-s approved these changes

2023-12-04 23:16 UTC, maackle approved these changes
This looks perfect! Encryption by default with a reasonable way to run tests unencrypted.

2023-12-22 10:19 UTC, ThetaSinner commented
Test flakes all sorted, the problem now is with the openssl build. This is happening on a couple of PRs and requires some Nix changes to stop using rustc directly when we do the standalone crate builds. Switching to something that uses Cargo directly should sort out this build issue but it's a blocker for this change for the moment.

2024-01-16 09:55 UTC, merged