install holochain binary in nix shell hook
holochain/holochain pull request #363
Opened 2020-09-17 06:28 UTC by thedavidmeister

2020-09-17 22:15 UTC, maackle requested changes
@thedavidmeister I dunno about this. Can't we just have an `hc-install` command for this? My concern is that there are already multiple binaries to be built (holochain, dna-util, and now lair), and you can't anticipate which one the user came to install. It's not really fair to make them wait for all of them to build (in release mode) before they can do anything.

2020-09-17 22:16 UTC, maackle commented
Especially if all they care about is debug builds, then it's just cruelty

2020-09-18 09:36 UTC, thedavidmeister commented
@maackle not sure, there's currently no way to get a `holochain` binary in the nix shell other than running `cargo install` and if we do nothing it points to the redux version, i feel this warrants discussion

install incrementally compiles so it is pretty fast after the first run

2020-09-18 15:17 UTC, maackle commented
We discussed and it led to the decision to soon have a hard cutoff on an upcoming holonix release that no longer includes the old holochain binary

2020-09-20 22:33 UTC, maackle commented on default.nix
> +   )])
@thedavidmeister people need to build `dna-util` as well. And maybe lair? So, should these be namespaced, `hc-install-holochain` etc?

2020-09-21 14:42 UTC, neonphog commented on default.nix
> +     rm $CARGO_INSTALL_ROOT/bin/dna-util
Why not `cargo uninstall` if nothing else just for symmetry with the install command?

Same with `hc-uninstall-holochain` above.

2020-09-21 19:21 UTC, maackle approved these changes
This set of commands looks good, but I agree with neonphog that we might as well use `cargo uninstall` instead of `rm`

2020-09-22 04:51 UTC, merged