Convert install app params to take agent key optionally
holochain/holochain pull request #389
Opened 2020-09-30 19:56 UTC by zippy

2020-10-01 18:47 UTC, maackle reviewed
I don't really like how this now allows two different ways to generate an agent key. If we go with this, we might as well just remove `GenerateAgentPubKey`, but it seems useful to be able to generate keys separately from the apps you're using them in. 

I'm not fully aware of the details of the bootstrapping problem that this solves, but I wonder why this is necessary, and if we shouldn't just make sure `GenerateAgentPubKey` just works in all cases.

2020-10-01 18:47 UTC, maackle commented on crates/holochain/src/conductor/api/api_external/admin_interface.rs
> +        };
Why'd you not use `assert_matches!` here?

2020-10-01 19:52 UTC, maackle requested changes
I want to make sure we need this first

2020-10-01 20:38 UTC, zippy commented
@maackle I think you might be right.  Will talk with @neonphog and @artbrock

2020-10-12 15:47 UTC, neonphog commented
I think we decided not to merge this for now. Feel free to re-open if that changes.

2020-10-12 15:47 UTC, closed without merging