Push Holochain tag separately
holochain/holochain pull request #4098
Opened 2024-07-16 17:04 UTC by ThetaSinner

### Summary

I hope this can go again if we were just needing one tag. Given that we push loads, this is the only decent solution I can think of for now. This gets around a github actions limitation that prevented my tag trigger working on the last release

### TODO:
- [ ] CHANGELOGs updated with appropriate info
- [ ] All code changes are reflected in docs, including module-level docs

2024-07-17 06:24 UTC, jost-s requested changes
Can't we just stop pushing tags for all packages right away? Or does the release automation depend on this in any way?

2024-07-17 11:00 UTC, ThetaSinner commented
The release automation reads crates.io, the previous releases listed in the changelog AND the tags to ensure that everything is consistent. Maybe we could sneak the tags out but I wouldn't feel confident making that change without breaking anything. 

I also think that while we're releasing at different versions, the tags are useful for finding where changes happened.

Unfortunately, for now I can't think of a simpler solution to this problem.

2024-07-19 08:32 UTC, jost-s commented
Grand so, then we keep this as is and look forward to the next gen release automation.

2024-07-19 08:33 UTC, jost-s approved these changes

2024-07-19 10:06 UTC, merged