Fix up unnecessary async blocking in zome calls
holochain/holochain pull request #4111
Opened 2024-07-22 05:47 UTC by maackle

### Summary

### TODO:
- [ ] CHANGELOGs updated with appropriate info
- [ ] All code changes are reflected in docs, including module-level docs

2024-07-23 18:22 UTC, maackle commented on crates/holochain/src/core/ribosome/guest_callback.rs
> +    // ribosome: RealRibosome,
```suggestion
```

2024-07-23 18:22 UTC, maackle commented on crates/holochain/src/core/ribosome/guest_callback.rs
> -                        // be truly async. Or at least make it a CallStream?
This PR was inspired by this comment

2024-07-23 18:24 UTC, maackle commented on crates/holochain/src/core/ribosome/host_fn/zome_info.rs
> +            tokio_helper::block_on(f, std::time::Duration::from_secs(60))
This is the only place where blocking needed to be reintroduced. This is offset by several places where a blocking thread previously needed to be spawned to accommodate a long-running sync task, and now those tasks are async and can run normally in tokio.

2024-07-24 06:07 UTC, jost-s reviewed
Looks good to me. Is there a test for the call iterator?

2024-07-24 16:45 UTC, maackle commented
> Looks good to me. Is there a test for the call iterator?

Just the one that was already there: https://github.com/holochain/holochain/pull/4111/files#diff-a7ceb4941355e4712ac6bf2b2ff32ef7fdd6e84069b62b3fbf808445fbf73ed6R75

2024-07-25 17:20 UTC, neonphog requested changes
@maackle - I don't know if I read this wrong, but it looks like this has been incorrect even before your change here:

https://github.com/holochain/holochain/blob/a764d8aeb1b5ba8118038db39721f5cfd7860a8e/crates/holochain/src/core/ribosome/real_ribosome.rs#L877-L879

`maybe_call` is being called within a tokio task, and appears to be running a blocking wasm call therefore hanging an entire tokio core thread and ALL tasks that happen to be assigned to that thread until the wasm call completes.

2024-07-30 19:30 UTC, maackle commented
@neonphog how does this look? https://github.com/holochain/holochain/pull/4111/commits/7b1a11d680a1af3988c5ceabb0e8ce31af699ba4

2024-07-30 19:44 UTC, neonphog commented
@maackle - Yes that looks better. Do you think this has the same problem?:

https://github.com/holochain/holochain/blob/develop/crates/holochain/src/core/ribosome/real_ribosome.rs#L945

2024-08-01 16:39 UTC, maackle commented
> Do you think this has the same problem?

@neonphog I guess const_fns are designed to return immediately, so maybe not, but it can't hurt right? So I spawned blocking on that too.

2024-08-01 16:44 UTC, neonphog approved these changes
woot, thanks!

2024-08-09 23:36 UTC, merged