[Integrity_types] linktag conversion traits
holochain/holochain pull request #4574
Opened 2024-12-19 18:28 UTC by nphias

### Summary
- overrides default SerialByte conversions for Linktag to make it easier to work with LinkTag and unsafebytes
- tests added 
note: 
- string conversions already existed
- Component to LinkTag conversions moved to a different issue
  
closes https://github.com/holochain/holochain/issues/2399

### TODO:
- [ ] CHANGELOGs updated with appropriate info
- [ ] All code changes are reflected in docs, including module-level docs

2024-12-23 18:39 UTC, mattyg commented on crates/holochain_integrity_types/src/link.rs
> +        //let back_to_sb = SerializedBytes::from(tag); //  -> also works
```suggestion
```

2024-12-23 19:00 UTC, mattyg commented on crates/holochain_integrity_types/src/link.rs
> +        Self(UnsafeBytes::from(sb).into())
```suggestion
        Self::new(sb.bytes().clone())
```

2024-12-23 19:03 UTC, mattyg requested changes
Nice thanks for this! Much easier to work with. Just requested 2 small changes inline.

This made me think of another potential ergonomics improvement that might be nice:

What if we added another derive macro `#[derive(LinkTagBytes)]` that we could apply to a struct to convert directly between it and a `LinkTag`, without needing to worry about `SerializedBytes`. What do you think?

2025-01-01 18:09 UTC, mattyg approved these changes

2025-01-03 13:24 UTC, ThetaSinner commented on crates/holochain/CHANGELOG.md
> +  - Added LinkTag helper trait functions to go into and out with serialized bytes
This needs to be under `Unreleased` further up

2025-01-03 13:24 UTC, ThetaSinner commented on crates/holochain_integrity_types/src/link.rs
> -
Retain newline between functions here please

2025-01-03 13:24 UTC, ThetaSinner commented on crates/holochain_integrity_types/src/link.rs
> +/// convert `LinkTag` into `SerializedBytes` (Infallible)
```suggestion
/// Convert a `LinkTag` into `SerializedBytes` (Infallible)
```

2025-01-03 13:24 UTC, ThetaSinner commented on crates/holochain_integrity_types/src/link.rs
> +/// Creates a `LinkTag` from `SerializedBytes` (Infallible)
```suggestion
/// Convert `SerializedBytes` into a `LinkTag` (Infallible)
```

2025-01-03 13:24 UTC, ThetaSinner commented on crates/holochain_integrity_types/src/link.rs
> +    }
```suggestion
    }

```

2025-01-03 13:24 UTC, ThetaSinner commented on crates/holochain_integrity_types/src/link.rs
> +        assert_eq!(location.latitude, back_to_location.latitude);
These objects should be equal

```suggestion
        assert_eq!(location, back_to_location);
```

and derive `PartialEq` on the `Data` type?

2025-01-03 18:01 UTC, ThetaSinner commented on crates/holochain/CHANGELOG.md
> +  - Added LinkTag helper trait functions to go into and out with serialized bytes
This looks like it's now under the `## 0.5.0-dev.11`? It needs to go right up to the `Unreleased` heading

2025-01-06 14:39 UTC, nphias commented on crates/holochain/CHANGELOG.md
> +- Added LinkTag helper trait functions to go into and out with serialized bytes
fixed

2025-01-06 15:15 UTC, ThetaSinner approved these changes
Fantastic, thank you!

2025-01-06 15:16 UTC, merged