Fix the slow timeout issue
holochain/holochain pull request #515
Opened 2020-11-30 11:39 UTC by freesig

This changes the rpc multi to only wait for the number of responses if their is actually remote agents. If there is less remote agents then the `target_node_count` is lowered to match.

2020-11-30 19:24 UTC, neonphog requested changes
I don't think I agree with this change.

To me, it feels like optimizing for a degenerate use-case.

If we have a healthy network, the most likely reason you were unable to connect to the requested number of nodes is because there was a connectivity hiccup. In which case, the proper course would be to give it some time for it to reconnect.

The entire point of the loop and timeout here is to allow time to pass for connectivity to be established or for peer discovery to be gossiped. If we arbitrarily reduce the desired node count, or worse, break out of the loop entirely if we don't find any nodes on our first attempt, there is no point to those devices.

If you don't want to wait 2 seconds for connectivity, lower the timeout for the specific use-case.
If you don't want to wait for more that 1 other remote node, lower the node count for the specific use-case.

2020-12-01 17:49 UTC, zippy commented
@neonphog ok, but where can/shoul we set these timeouts and counts?  In networking config?  Enviornment variables? Per happ as and admin call?

2020-12-02 18:34 UTC, neonphog commented
@zippy 

> @neonphog ok, but where can/should we set these timeouts and counts? In networking config? Enviornment variables? Per happ as and admin call?

My vote would be plumbed all the way through to the hdk, then developers have the flexibility to configure them via dna properties on one end of the spectrum all the way to pushing the responsibility up to the UI.

2020-12-02 20:27 UTC, zippy commented
> @zippy
> 
> > @neonphog ok, but where can/should we set these timeouts and counts? In networking config? Enviornment variables? Per happ as and admin call?
> 
> My vote would be plumbed all the way through to the hdk, then developers have the flexibility to configure them via dna properties on one end of the spectrum all the way to pushing the responsibility up to the UI.

Hmmm...  One of my big learning from redux, was that it was exceptionally easy to make timeout mistakes across layers that had very bad consequences.  i.e. we had timeouts set by app developers that were much longer than timeouts set internally in holochain that then created retry-queueing buildup, and also didn't make sense because they didn't jibe with timeouts set by receiving nodes for responses, etc.   I recall that one of the things we talked about at the beginning of RSM build out was to push most of the timeout intelligence into the kitsune layer because of this.

For this "plumbing all the way through" to actually function would, I think, require significant systems integrity checking.

2020-12-02 21:16 UTC, neonphog commented
@zippy 

> One of my big learning from redux, was that it was exceptionally easy to make timeout mistakes across layers that had very bad consequences ... I recall that one of the things we talked about at the beginning of RSM build out was to push most of the timeout intelligence into the kitsune layer because of this.

My understanding of what came out of that conversation was exactly what I'm suggesting... that we don't have any mystery magic timeouts - the one single timeout to rule them all is managed at the lowest level - Kitsune - but controllable at the highest level - by the app dev.

2020-12-03 10:48 UTC, freesig commented
Todo:
- [ ] extract the tests from this pr as they are useful and close it without merging.

2020-12-03 10:52 UTC, freesig commented
I think [this approach](https://github.com/holochain/holochain/pull/518) is closer to what we want. The HDK can specify what kind of call they want to do (block till best effort vs return just what I have) rather then timeouts as @zippy mentioned timeouts are hard to get right and probably need to be managed in a smarter way at the kitesune level based on health etc. but on the other hand the happ devs could help by expressing their intentions for the call at the hdk level. Would love some feed back on the conversation in that thread

2020-12-03 20:58 UTC, neonphog commented
Closing, feel free to re-open if appropriate.

2020-12-03 20:58 UTC, closed without merging