2020 12 01 secretbox
holochain/holochain pull request #524
Opened 2020-12-04 13:39 UTC by thedavidmeister

2020-12-04 18:47 UTC, neonphog commented on crates/zome_types/src/lib.rs
> +/// random bytes and sending them to peers directly.
From an infosec perspective, you should just never do this. This is the point of asynchronous crypto - individuals generate keypairs and keep their private keys private, only publishing public keys.

I worry about publishing an API that encourages bad practices.

2020-12-04 18:50 UTC, neonphog commented on crates/zome_types/src/lib.rs
> +///    references to the secret data.
Either / both of these are totally valid strategies to base our API on - we don't even need lair to be implemented yet, we can keep the private keys unprotected in holochain for the moment, but write the WASM api properly to interact with handles or key exchange mechanisms so app devs don't go down an insecure path with their code, right?

2020-12-04 19:12 UTC, neonphog requested changes
From some of the comments here, I'm getting the impression you are trying to effect a membership-based encryption where a curated group is given access keys to decrypt publicly available messages?

Would what you are trying to accomplish be better supported by a classic key ring implementation? Like, the symmetric key is asymmetrically encrypted separately for each member of the group / set of messages, and membership is the act of an existing member re-encrypting that key for that agent's public key?

I'm not meaning to shut you down, totally just trying to have a conversation before we bake a behavior into our API.

2020-12-05 01:53 UTC, thedavidmeister commented
> From some of the comments here, I'm getting the impression you are trying to effect a membership-based encryption where a curated group is given access keys to decrypt publicly available messages?
> 
> Would what you are trying to accomplish be better supported by a classic key ring implementation? Like, the symmetric key is asymmetrically encrypted separately for each member of the group / set of messages, and membership is the act of an existing member re-encrypting that key for that agent's public key?
> 
> I'm not meaning to shut you down, totally just trying to have a conversation before we bake a behavior into our API.

@neonphog yes, that's why i put "'box' for keypair based encryption" as the next item on the list, so you can box up a secretbox key, e.g. how saltpack does it

we need to _have_ a symmetric key before we can encrypt it though :sweat_smile: 

> Either / both of these are totally valid strategies to base our API on - we don't even need lair to be implemented yet, we can keep the private keys unprotected in holochain for the moment, but write the WASM api properly to interact with handles or key exchange mechanisms so app devs don't go down an insecure path with their code, right?

@neonphog both are useful in different contexts, so it would be good to have them both

i think when i wrote this i was thinking that it would be too limiting to _force_ it to work this way but now that i've slept on it and have a fresh coffee, i'd like to design something that works better here :coffee:

2020-12-18 17:12 UTC, neonphog approved these changes
Nice!

2020-12-18 17:19 UTC, thedavidmeister commented
over here for the combined PR :) - https://github.com/holochain/holochain/pull/559

2020-12-18 17:19 UTC, closed without merging