Remove unused use-statement
holochain/holochain pull request #637
Opened 2021-02-10 16:47 UTC by lucksus

2021-02-15 06:26 UTC, freesig approved these changes

2021-02-15 06:27 UTC, freesig requested changes
This doesn't pass CI?

2021-02-17 02:00 UTC, maackle commented
Perhaps it's used after all?

2021-03-11 17:30 UTC, neonphog commented
Erm... CI is passing now, but there is no longer a diff with develop - perhaps this got fixed elsewhere? Closing.

2021-03-11 17:30 UTC, closed without merging