adds systemd ready notification to main conductor process
holochain/holochain pull request #739
Opened 2021-04-18 07:04 UTC by peeech

Adds ability to send a notification to systemd that holochain is ready for interactions. This feature is important when holochain is running as a systemd unit and there are other units depending on holocahin's readiness.

2021-04-18 14:48 UTC, neonphog requested changes
Maybe I'm missing it, but I don't see any conditional compilation in this library, so we'll need to:

```
[target.'cfg(unix)'.dependencies]
sd-notify = "0.3.0"
```
and 

`#[cfg(unix)]` the usage bits.

2021-04-19 12:58 UTC, peeech commented
> `#[cfg(unix)]` the usage bits.

Good point! Added in 12e990f

2021-04-19 19:26 UTC, neonphog commented on crates/holochain/src/bin/holochain/main.rs
> +use sd_notify::{notify, NotifyState};
```suggestion
#[cfg(unix)]
use sd_notify::{notify, NotifyState};
```

2021-04-19 19:27 UTC, neonphog approved these changes
looks good pending the one additional #cfg

2021-04-20 03:00 UTC, merged