Kitsune arcsets pt 1: Simplify arc queries to use a single range
holochain/holochain pull request #816
Opened 2021-06-08 22:35 UTC by maackle

2021-06-09 05:43 UTC, maackle commented on crates/holochain_sqlite/src/sql/cell/fetch_op_hashes.sql
> +SELECT
Oops, I missed a set of parens, I fixed it in a commit and now I'm seeing that it's using the indexes

2021-06-09 05:47 UTC, maackle commented on crates/holochain_sqlite/src/sql/cell/fetch_op_hashes.sql
> +SELECT
Although it's only using the timestamp index, not the storage_loc index, so maybe that's no good

2021-06-09 09:23 UTC, freesig commented on crates/holochain_sqlite/src/sql/cell/fetch_op_hashes.sql
> +SELECT
It really depends. Is the timestamp likely to shrink the search space a lot? If not you're better off using the storage index which won't work due to the or.
I don't really see the point to this tbh. 
This line `:storage_start_loc <= :storage_end_loc` can just be tested on the rust side and run a different sql query depending on the outcome. What is the reason for needing it in the sql?

2021-06-17 01:23 UTC, freesig approved these changes
NIcce

2021-06-24 19:48 UTC, neonphog commented on crates/kitsune_p2p/types/src/dht_arc.rs
> +    pub fn primitive_range_transposed(&self) -> (Option<u32>, Option<u32>) {
Just a semantic thing, but I don't like the name "transposed" it makes me think you're inverting the arc / selecting all the non-selected arc-space by swapping the start/end values.

Though, I'm having trouble coming up with a better name... maybe the two values are "detached" from each other?

```suggestion
    pub fn primitive_range_detached(&self) -> (Option<u32>, Option<u32>) {
```

2021-06-24 20:04 UTC, neonphog commented on crates/holochain_sqlite/src/sql/p2p_agent_store/gossip_query.sql
> +          OR storage_center_loc > :storage_start_loc
Even though it wraps around, the marked points are still inclusive, so this needs to be <= / >= no?

```suggestion
          storage_center_loc <= :storage_end_loc
          OR storage_center_loc >= :storage_start_loc
```

2021-06-24 20:05 UTC, neonphog requested changes
inclusive wrapping range

2021-06-24 22:37 UTC, neonphog approved these changes
woot

2021-06-25 20:44 UTC, merged