Expand App status to include Enabled/Disabled and Running/Stopped distinctions
holochain/holochain pull request #858
Opened 2021-06-28 21:17 UTC by maackle

TODO:

- [ ] changelog

2021-07-02 15:57 UTC, neonphog commented on crates/holochain/src/conductor/api/api_external/admin_interface.rs
>                  Ok(AdminResponse::ActiveAppsListed(app_ids))
should this be EnabledAppsListed?

2021-07-02 16:00 UTC, neonphog commented on crates/holochain/src/conductor/api/api_external/admin_interface.rs
> +            }
correct me if I'm wrong, but it looks to me like these deprecated calls are still returning the new results, so they wouldn't be compatible anyways? If that's true we should either not bother with the deprecation, or implement it fully with the result types as well.

2021-07-02 16:02 UTC, neonphog commented on crates/holochain/src/conductor/conductor.rs
> +            cell.cell.cleanup().await?;
is this cleanup likely to take time? perhaps we should return this for processing after the lock is released?

2021-07-02 16:08 UTC, neonphog commented on crates/holochain/src/conductor/manager/error.rs
> +                _ => todo!("identify all recoverable cases"),
is this used yet? we may not want to merge this if it'll cause panics for unspecified error types

2021-07-02 16:16 UTC, neonphog requested changes
Couple things need looking at.

You can probably ignore the async cleanup holding open the lock comment... after looking through here, I see how everything else cell state related is doing that / understand why you were looking at cleaning that up.

I think it'll make sense to do in the not-to-distant future... it's no surprise when holo hammers a bunch of app installs all at once they take forever : )

2021-07-02 16:17 UTC, neonphog commented on crates/holochain/src/conductor/conductor.rs
> +            cell.cell.cleanup().await?;
can probably ignore this, given this is the state of the other calls in here : )

2021-07-05 22:48 UTC, neonphog approved these changes
@maackle - It still looks to me like there's a disconnect in the deprecated API...

I.e. on success, `ListEnabledApps` will give you an `EnabledAppsListed` struct, and the deprecated `ListActiveApps` will *also* give you an `EnabledAppsListed` struct, where previously it gave you an `ActiveAppsListed` struct... so won't this break clients using the deprecated api?

You're more familiar with the usage, so maybe this isn't a big deal. And otherwise looks good :+1:

2021-07-05 23:13 UTC, maackle commented
@neonphog ah yes I meant to mention this -- I believe the struct name doesn't show up in the serialized response data, and the structure is the same for all of these deprecated structs and their counterparts, it should be OK.

2021-07-07 19:44 UTC, merged